language: python
sudo: false
dist: trusty

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - libblas-dev
      - liblapack-dev
      - libopenblas-dev
      - cmake
      - cmake-data
      - swig
      - libav-tools
      - libboost-all-dev
      - libjpeg-dev
      - zlib1g-dev
      - gfortran
      - python-dev
      - python-numpy
      - python-scipy

install:
  #dependeicies via pip
  - travis_wait pip install six cython
  - travis_wait pip install pandas scikit-learn matplotlib
  - travis_wait pip install nose nose-parameterized
  - travis_wait pip install -r requirements.txt
  # intalling AgentNet
  - pip install .
  # installing Gym
  - git clone https://github.com/openai/gym.git
  - cd gym && pip install -e . && cd ..
  - cd gym && pip install -e '.[atari]' && cd ..
  - cd gym && pip install -e '.[classic_control]' && cd ..

script:
  - nosetests tests --verbose --nocapture  --failure-detail
